name: Theme Cards Demo CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm

      - name: Generate Site
        run: |
          git clone --depth=1 https://github.com/ChrAlpha/theme-cards-docs docs
          npm --prefix ./docs install
          npm --prefix ./docs run build

          mkdir -p ./dist
          cp -rf ./docs/public/. ./dist

          git clone --depth=1 https://github.com/ChrAlpha/hexo-theme-cards.git themes/cards
          npm ci
          npm run build
          mkdir -p ./dist/demo
          cp -rf ./public/. ./dist/demo

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_KEY }}
          external_repository: ChrAlpha/theme-cards-site
          publish_dir: ./dist
          publish_branch: gh-pages
          cname: theme-cards.ichr.me
          allow_empty_commit: true
          force_orphan: true
